name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Secrets
      run: |
        if [ -z "${{ secrets.AWS_REGION }}" ]; then echo "REGION is EMPTY"; else echo "REGION is SET"; fi
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then echo "KEY is EMPTY"; else echo "KEY is SET"; fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Backend to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/task-backend:$IMAGE_TAG ./app/backend
        docker push $ECR_REGISTRY/task-backend:$IMAGE_TAG

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name task-manager-cluster --region eu-north-1

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Injectăm imaginea nouă
        sed -i "s|image: .*|image: $ECR_REGISTRY/task-backend:$IMAGE_TAG|g" k8s/backend-deploy.yaml
        
        # Injectăm endpoint-ul RDS (căutăm linia de după DB_HOST)
        sed -i "/name: DB_HOST/{n;s|value: \".*\"|value: \"${{ secrets.RDS_HOSTNAME }}\"|}" k8s/backend-deploy.yaml
        
        kubectl apply -f k8s/backend-deploy.yaml
